### ISSUE TITLE
don't use It corrupts startup

### ISSUE THREAD

**Issue by footballs** [dashjuvi/al-khaser-but-compiled#3]

**Comment by dashjuvi** [comment]
It does not

**Comment by footballs** [comment]
Brother I tested on both vm and my pc. Once you will run and restart, it will came up with that cmd with black empty background of desktop and nothing there else that console window. But thanks for exe.

**Comment by footballs** [comment]
I just wanted to report it.
I am using windows 7 super lite edition & I am not lie ing.
https://archive.org/details/windows7superlitesp1

but anyway thanks I get to manage to test al-khaser.
